apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k3s-manifest
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: osrm-backend-custom
  name: osrm-backend-custom
spec:
  ports:
    - name: "5004"
      port: 5004
      targetPort: 5004
  selector:
    io.kompose.service: osrm-backend-custom
