apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k3s-manifest
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: osrm-backend-foot
  name: osrm-backend-foot
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 5003
  selector:
    io.kompose.service: osrm-backend-foot
