apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k3s-manifest
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: osrm-backend-bicycle
  name: osrm-backend-bicycle
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: osrm-backend-bicycle
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o k3s-manifest
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: osrm-backend-bicycle
    spec:
      containers:
        - args:
            - osrm-routed
            - -p
            - "5002"
            - --mmap
            - --threads
            - "4"
            - --algorithm
            - mld
            - --max-matching-size
            - "10000"
            - /data/bicycle.uswest_wrongways/us-west-latest.osrm
          image: ghcr.io/project-osrm/osrm-backend:v5.27.1
          name: osrm-backend-bicycle
          ports:
            - containerPort: 5002
              protocol: TCP
          resources:
            limits:
              memory: "8589934592"
          volumeMounts:
            - mountPath: /data
              name: osrm-data
      restartPolicy: Always
      volumes:
        - name: osrm-data
          persistentVolumeClaim:
            claimName: osrm-data
